RECORD_0816_YNQFV = {
    "qr-cv": "8:16",
    "qr-lc-proposed": "יֹ֭נַקְתּ֥וֹ",
    "qr-what-is-weird": "דחי not געיה",
    "qr-consensus": "יֹֽנַקְתּ֥וֹ",
    "qr-generic-comment": [
        "Above I have asserted that the consensus has געיה here,",
        " but this געיה, like most cases of געיה, is optional.",
        " Therefore, one could just as easily assert the consensus has no געיה.",
        " I have chosen the consensus to be as close as possible",
        " to the proposed transcription of μL.",
        " I did this in order to make the proposed transcription",
        " seem no weirder than it really is.",
        " In other words, it is better to frame this as a question of דחי versus געיה",
        " than as a question of דחי versus no mark at all.",
    ],
    "qr-highlight": 1,
    "qr-lc-loc": {"page": "399A", "column": 2, "line": -4},
    "qr-noted-by": "tBHQ-zmiscWLC",
}
