# Initially generated by GitHub Copilot.
"""
Run all check scripts for the codex-index-cam1753 project.

Checks run:
  1. check_word_finding  (word-finding against book-of-job quirkrecs)

Exit codes:
  0 - All checks passed
  1 - One or more checks failed

Usage:
  python check_all.py
"""

import sys

import check_word_finding

_SEPARATOR = "\u2500" * 60


def main():
    checks = [
        ("Word finding (book-of-job quirkrecs)", check_word_finding.main),
    ]

    failures = []
    for label, run_fn in checks:
        print(f"\n{_SEPARATOR}")
        print(f"  {label}")
        print(_SEPARATOR)
        rc = run_fn()
        if rc:
            failures.append(label)

    print(f"\n{'=' * 60}")
    if failures:
        print(f"FAILED ({len(failures)} of {len(checks)}):")
        for f in failures:
            print(f"  - {f}")
        return 1
    else:
        print(f"All {len(checks)} checks passed.")
        return 0


if __name__ == "__main__":
    sys.exit(main())
