# Initially generated by GitHub Copilot.
"""
Run all check scripts for the codex-index-cam1753 project.

Checks run:
  1. check_word_finding      (word-finding against book-of-job quirkrecs)
  2. check_mark_order        (Hebrew combining-mark order, SBL2)
  3. check_escape_sequences  (literal chars instead of \\uXXXX escapes)
  4. check_line_breaks       (line-break JSON consistency)

Exit codes:
  0 - All checks passed
  1 - One or more checks failed

Usage:
  python check_all.py
"""

import sys

import check_escape_sequences
import check_line_breaks
import check_mark_order
import check_word_finding

_SEPARATOR = "─" * 60


def _run_line_breaks():
    """Wrapper for check_line_breaks.main() which calls sys.exit()."""
    saved_argv = sys.argv
    sys.argv = [sys.argv[0], "--no-open"]
    try:
        check_line_breaks.main()
        return 0  # main() returned normally (shouldn’t happen, but handle it)
    except SystemExit as exc:
        return exc.code if exc.code is not None else 0
    finally:
        sys.argv = saved_argv


def main():
    checks = [
        ("Word finding (book-of-job quirkrecs)", check_word_finding.main),
        ("Hebrew mark order (SBL2)", check_mark_order.main),
        ("Escape sequences (literal chars)", check_escape_sequences.main),
        ("Line-break JSON consistency", _run_line_breaks),
    ]

    failures = []
    for label, run_fn in checks:
        print(f"\n{_SEPARATOR}")
        print(f"  {label}")
        print(_SEPARATOR)
        rc = run_fn()
        if rc:
            failures.append(label)

    print(f"\n{'=' * 60}")
    if failures:
        print(f"FAILED ({len(failures)} of {len(checks)}):")
        for f in failures:
            print(f"  - {f}")
        return 1
    else:
        print(f"All {len(checks)} checks passed.")
        return 0


if __name__ == "__main__":
    sys.exit(main())
