# Initially generated by GitHub Copilot.
"""Fix non-standard Hebrew mark order in .py and .json files."""

import re
from pathlib import Path

from pycmn.uni_denorm import give_std_mark_order

ROOT = Path(__file__).resolve().parent

WORD_RE = re.compile(r"[\u0590-\u05FF\u034F\uFB1E]+")
HAS_LETTER_RE = re.compile(r"[\u05D0-\u05EA]")

_SKIP_DIRS = {".venv", "__pycache__", ".novc", ".git", "node_modules"}


def fix_line(line):
    parts = []
    last_end = 0
    for m in WORD_RE.finditer(line):
        word = m.group()
        parts.append(line[last_end : m.start()])
        if HAS_LETTER_RE.search(word):
            parts.append(give_std_mark_order(word))
        else:
            parts.append(word)
        last_end = m.end()
    parts.append(line[last_end:])
    return "".join(parts)


for p in sorted(ROOT.rglob("*")):
    if any(part in _SKIP_DIRS for part in p.parts):
        continue
    if not (p.is_file() and p.suffix in (".py", ".json")):
        continue
    text = p.read_text(encoding="utf-8")
    lines = text.split("\n")
    new_lines = [fix_line(line) for line in lines]
    new_text = "\n".join(new_lines)
    if new_text != text:
        p.write_text(new_text, encoding="utf-8")
        print(f"Fixed: {p.relative_to(ROOT)}")
    else:
        pass  # no changes
