# Initially generated by GitHub Copilot.
"""
Cambridge MS Add. 1753 word-image utilities.

Provides functions to locate Hebrew words in cam1753 line-break data,
compute bounding boxes from quad column-coordinate files, load page
images, and generate crop overlays for interactive editing.

Import from submodules directly:
    from py_cam1753_word_image.page import ...
    from py_cam1753_word_image.crop import ...
    from py_cam1753_word_image.hebrew_metrics import ...
    from py_cam1753_word_image.linebreak_search import ...
"""
