# Initially generated by GitHub Copilot.
"""
Cambridge MS Add. 1753 word-image utilities.

Provides functions to locate Hebrew words in cam1753 line-break data,
compute bounding boxes from quad column-coordinate files, load page
images, and generate crop overlays for interactive editing.
"""

from .crop import compute_fade_overlay, estimate_word_position
from .hebrew_metrics import (
    HEB_WIDTHS,
    SPACE_WIDTH,
    join_maqaf,
    line_widths,
    strip_heb,
    word_width,
)
from .linebreak_search import find_word_in_linebreaks
from .page import (
    IMG_DIR,
    LB_DIR,
    LINES_PER_COL,
    QUAD_DIR,
    ROOT,
    find_page_for_verse,
    get_line_bbox,
    load_page_image,
)
