# Initially generated by GitHub Copilot.
"""Hebrew text utilities: width metrics, stripping, maqaf joining."""

import unicodedata


def strip_heb(s):
    """Strip cantillation marks, vowels, and format chars from Hebrew text for matching."""
    out = []
    for ch in s:
        cat = unicodedata.category(ch)
        # Keep letters (Lo) and punctuation (Po for maqaf etc.),
        # skip Mn (marks) and Cf (format chars like ZWJ U+200D)
        if cat not in ("Mn", "Cf"):
            out.append(ch)
    return "".join(out)


def join_maqaf(words):
    """Join maqaf-ending words with the following word. Returns new list."""
    result = []
    for w in words:
        if result and result[-1].endswith("־"):
            result[-1] = result[-1] + w
        else:
            result.append(w)
    return result


# Relative width metrics for Hebrew characters (proportional, not monospace).
# Based on typical manuscript/printed Hebrew proportions.
# Values are relative to an "average" letter width of 1.0.
HEB_WIDTHS = {
    # Very narrow
    "י": 0.4,  # yod
    "ו": 0.5,  # vav
    "ן": 0.5,  # nun sofit
    # Narrow
    "ז": 0.6,  # zayin
    "ג": 0.7,  # gimel
    "ר": 0.7,  # resh
    "ך": 0.7,  # kaf sofit
    "ף": 0.7,  # pe sofit
    # Medium
    "ב": 0.85,  # bet
    "ד": 0.85,  # dalet
    "ה": 0.9,  # he
    "כ": 0.85,  # kaf
    "ל": 0.7,  # lamed
    "נ": 0.7,  # nun
    "ע": 0.9,  # ayin
    "פ": 0.9,  # pe
    "ץ": 0.8,  # tsade sofit
    "צ": 0.8,  # tsade
    "ק": 0.9,  # qof
    "ת": 0.9,  # tav
    # Wide
    "א": 1.0,  # alef
    "ח": 1.0,  # chet
    "ט": 1.0,  # tet
    "מ": 1.0,  # mem
    "ס": 1.0,  # samekh
    "ש": 1.1,  # shin
    # Very wide
    "ם": 1.1,  # mem sofit
    # Punctuation
    "־": 0.6,  # maqaf
    "׀": 0.3,  # paseq
    "׃": 0.3,  # sof pasuq
    "\u003a": 0.3,  # colon (sometimes used for sof pasuq in data)
}

# Inter-word space
SPACE_WIDTH = 0.5


def word_width(word):
    """Estimate the rendered width of a Hebrew word using character metrics."""
    w = 0.0
    for ch in word:
        cat = unicodedata.category(ch)
        if cat == "Mn":
            # Combining marks (vowels, accents) have zero width
            continue
        w += HEB_WIDTHS.get(ch, 0.85)  # default to average
    return w


def line_widths(words):
    """Return list of word widths and total line width including spaces."""
    word_ws = [word_width(w) for w in words]
    spaces = SPACE_WIDTH * max(0, len(words) - 1)
    total = sum(word_ws) + spaces
    return word_ws, total
