# Initially generated by GitHub Copilot.
"""Hebrew text utilities: width metrics, stripping, maqaf joining."""

import unicodedata


def strip_heb(s):
    """Strip cantillation marks, vowels, and format chars from Hebrew text for matching."""
    out = []
    for ch in s:
        cat = unicodedata.category(ch)
        # Keep letters (Lo) and punctuation (Po for maqaf etc.),
        # skip Mn (marks) and Cf (format chars like ZWJ U+200D)
        if cat not in ("Mn", "Cf"):
            out.append(ch)
    return "".join(out)


def join_maqaf(words):
    """Join maqaf-ending words with the following word. Returns new list."""
    result = []
    for w in words:
        if result and result[-1].endswith("\N{HEBREW PUNCTUATION MAQAF}"):
            result[-1] = result[-1] + w
        else:
            result.append(w)
    return result


# Relative width metrics for Hebrew characters (proportional, not monospace).
# Based on typical manuscript/printed Hebrew proportions.
# Values are relative to an "average" letter width of 1.0.
HEB_WIDTHS = {
    # Very narrow
    "\N{HEBREW LETTER YOD}": 0.4,
    "\N{HEBREW LETTER VAV}": 0.5,
    "\N{HEBREW LETTER FINAL NUN}": 0.5,
    # Narrow
    "\N{HEBREW LETTER ZAYIN}": 0.6,
    "\N{HEBREW LETTER GIMEL}": 0.7,
    "\N{HEBREW LETTER RESH}": 0.7,
    "\N{HEBREW LETTER FINAL KAF}": 0.7,
    "\N{HEBREW LETTER FINAL PE}": 0.7,
    # Medium
    "\N{HEBREW LETTER BET}": 0.85,
    "\N{HEBREW LETTER DALET}": 0.85,
    "\N{HEBREW LETTER HE}": 0.9,
    "\N{HEBREW LETTER KAF}": 0.85,
    "\N{HEBREW LETTER LAMED}": 0.7,
    "\N{HEBREW LETTER NUN}": 0.7,
    "\N{HEBREW LETTER AYIN}": 0.9,
    "\N{HEBREW LETTER PE}": 0.9,
    "\N{HEBREW LETTER FINAL TSADI}": 0.8,
    "\N{HEBREW LETTER TSADI}": 0.8,
    "\N{HEBREW LETTER QOF}": 0.9,
    "\N{HEBREW LETTER TAV}": 0.9,
    # Wide
    "\N{HEBREW LETTER ALEF}": 1.0,
    "\N{HEBREW LETTER HET}": 1.0,
    "\N{HEBREW LETTER TET}": 1.0,
    "\N{HEBREW LETTER MEM}": 1.0,
    "\N{HEBREW LETTER SAMEKH}": 1.0,
    "\N{HEBREW LETTER SHIN}": 1.1,
    # Very wide
    "\N{HEBREW LETTER FINAL MEM}": 1.1,
    # Punctuation
    "\N{HEBREW PUNCTUATION MAQAF}": 0.6,
    "\N{HEBREW PUNCTUATION PASEQ}": 0.3,
    "\N{HEBREW PUNCTUATION SOF PASUQ}": 0.3,
    "\u003a": 0.3,  # colon (sometimes used for sof pasuq in data)
}

# Inter-word space
SPACE_WIDTH = 0.5


def word_width(word):
    """Estimate the rendered width of a Hebrew word using character metrics."""
    w = 0.0
    for ch in word:
        cat = unicodedata.category(ch)
        if cat == "Mn":
            # Combining marks (vowels, accents) have zero width
            continue
        w += HEB_WIDTHS.get(ch, 0.85)  # default to average
    return w


def line_widths(words):
    """Return list of word widths and total line width including spaces."""
    word_ws = [word_width(w) for w in words]
    spaces = SPACE_WIDTH * max(0, len(words) - 1)
    total = sum(word_ws) + spaces
    return word_ws, total
